# Security header/ Digital Designers 
# Implemented for https://corey-david.ca

[build]
  publish = "_site"
  command = "npm run build"

[[headers]]
  for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Cross-Origin-Resource-Policy = "same-site"
  Cross-Origin-Embedder-Policy = "same-origin"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "upgrade-insecure-requests"
  Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
  Strict-Transport-Security = '''
  max-age=63072000;
  includeSubDomains;
  preload'''

# Netlify
 [[redirects]]
 from = "https://corey-david.netlify.app"
 to = "https://corey-david.ca"
 status = 301
 force = true

# social media

# feeds
[[redirects]]
from = "/feed"
to = "/feed.xml"
status = 301
force = true

[[redirects]]
from = "/rss"
to = "/rss.xml"
status = 301
force = true

[[redirects]]
from = "/sitemap"
to = "/sitemap.xml"
status = 301
force = true